# Generated by Django 5.0.6 on 2024-07-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('adhar_no', models.CharField(max_length=12)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
            ],
        ),
    ]
