# Generated by Django 5.0.6 on 2024-07-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('sport', models.CharField(max_length=45)),
                ('team', models.CharField(max_length=45)),
            ],
        ),
    ]
