# Generated by Django 5.0.6 on 2024-07-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Football',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
            ],
        ),
    ]
