# Generated by Django 5.0.6 on 2024-07-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('company', models.CharField(max_length=45)),
                ('designation', models.CharField(max_length=45)),
            ],
        ),
    ]
