# Generated by Django 5.0.6 on 2024-07-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('model', models.CharField(max_length=45)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
